image: node:16-buster

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  only:
    - tags
    - merge_requests
  script:
    - npm i
    - npm run lint
    - npm run
    - npm run detect-circular-deps
    - npm run test:all

deploy-npm:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "master"
  script:
    - git config --global user.email "info@evam.life"
    - git config --global user.name "Evam Bot"
    - npm config set registry https://registry.npmjs.org/
    - npm version "$CI_COMMIT_TAG"
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm install
    - npm run build
    - npm publish --access public

deploy-npm-preview:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH != "master"
  script:
    - git config --global user.email "info@evam.life"
    - git config --global user.name "Evam Bot"
    - npm config set registry https://registry.npmjs.org/
    - npm version "$CI_COMMIT_TAG"
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm install
    - npm run build
    - npm publish --access public --tag preview
