image: node:16-buster

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  only:
    - tags
    - merge_requests
  script:
    - npm install
    - npm test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

deploy:
  stage: deploy
  only:
    - tags
  variables:
    REPO_ID: 4
  script:
    - git config --global user.email "info@evam.life"
    - git config --global user.name "Evam Bot"
    - npm version "$CI_COMMIT_TAG"
    - echo "@evam:registry=https://www.developers.evam.life/api/v4/projects/$REPO_ID/packages/npm/" > ~/.npmrc
    - echo "//www.developers.evam.life/api/v4/projects/$REPO_ID/packages/npm/:_authToken=${DEV_PORTAL_BOT_AUTH_TOKEN}" >> ~/.npmrc
    - head -c 150 ~/.npmrc
    - npm install
    - npm run build
    - npm run pub
