image: node:16-buster

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  only:
    - tags
    - merge_requests
  script:
    - npm install
    - npm test
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

deploy:
  stage: test
  only:
    - tags
  variables:
    REPO_ID: 36450111
  script:
    - git config --global user.email "florian@evam.life"
    - git config --global user.name "Florian Curinga"
    - npm version "$CI_COMMIT_TAG"
    - echo "@evam:registry=https://gitlab.com/api/v4/projects/$REPO_ID/packages/npm/" > ~/.npmrc
    - echo "//gitlab.com/api/v4/projects/$REPO_ID/packages/npm/:_authToken=$GITLAB_COM_AUTH_TOKEN" >> ~/.npmrc
    - cat .npmrc
    - npm install
    - npm run build
    - npm run pub
