image: node:16-buster

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  only:
    - tags
    - merge_requests
  script:
    - npm install
    - npm build
    - npm test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

deploy-npm:
  stage: deploy
  only:
    - tags
  script:
    - git config --global user.email "info@evam.life"
    - git config --global user.name "Evam Bot"
    - npm config set registry https://registry.npmjs.org/
    - npm version "$CI_COMMIT_TAG"
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm install
    - npm run build
    - npm publish --access public
