image: node:16-buster

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  only:
    - tags
    - merge_requests
  script:
    - npm install --legacy-peer-deps
    - npm run build
    - npm test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

deploy-npm:
  stage: deploy
  only:
    - tags
  script:
    - git config --global user.email "info@evam.life"
    - git config --global user.name "Evam Bot"
    - npm config set registry https://registry.npmjs.org/
    - npm version "$CI_COMMIT_TAG"
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm install
    - npm run build
    - bash -c 'if [[ "$CI_COMMIT_TAG" == *"beta"* ]]; then echo "Pushing beta" && npm publish --access public --tag beta; else echo "Pushing prod" && npm publish --access public; fi'
